development:
  stripe_publishable_key: pk_test_JfE3TjzRi3FfyJX0zPcvCJDI
  stripe_secret_key: sk_test_03TVUwoWwKqs8frDinxUa0DQ

production:
  stripe_publishable_key: pk_live_h68v5iuUiP7ehf0KmHJq9mUC
  stripe_secret_key: sk_live_lvhAiMjFPgTjpDTDKDFj9uZz
